### ISSUE TITLE
Ensure decoding an invalid ID with a repeating reserved character does not crash

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-haskell#3]
Spec has been adjusted to include an additional check: https://github.com/sqids/sqids-spec/commit/f52b57836b0463097018f984f853b284e50a5ce4

What happens without that check is that when a reserved character (eg: offset character) is removed from the alphabet during decoding, conversion from ID to number becomes impossible when that same character is once again present in the ID (under normal conditions this never happens during encoding).

The best way to check for this is to try & decode an ID `fff` (like in the above link). Please ensure the library tests for that & returns an empty array under these conditions.

**Comment by laserpants** [comment]
Fixed in https://github.com/sqids/sqids-haskell/commit/57ddfe3a9c14f1ef938cf2e828039516716f4643.

- :package: Released as [version 0.1.3.0](https://hackage.haskell.org/package/sqids-0.1.3.0)
- :label: Tag is [here](https://github.com/sqids/sqids-haskell/releases/tag/v0.1.3.0)

cc: @4kimov

**Comment by laserpants** [comment]
(test was added here: https://github.com/sqids/sqids-haskell/commit/a32ddd4501f0564605b5e3257df2c74f005ae94a)
